//
//  IPConfiguration.swift
//  IPificationSDK
//
//  Created by IPification Mobile on 3/6/2021.
//  Copyright © 2021 IPification Mobile. All rights reserved.
//

import Foundation

/// Selects the IPification backend environment used by the SDK.
public enum IPEnvironment {
    /// The sandbox environment for development and integration testing.
    case SANDBOX
    /// The production environment for live traffic.
    case PRODUCTION
    /// The custom environment for new DC
    case CUSTOM
}
/// Stores global settings used by IPification SDK services.
///
/// Configure the shared instance before starting coverage or authentication requests.
public class IPConfiguration : NSObject {
    /// The semantic version of this SDK build.
    public let CURRENT_VERSION : String = "2.2.0"
    /// The SDK platform identifier included in backend requests.
    public let SDK_TYPE_VALUE = "native"
    /// Controls whether requests include carrier and device headers generated by the SDK.
    public var enableCarrierHeaders: Bool = true
    /// The number of random bytes used when generating an authorization state value.
    public var STATE_LENGTH: Int = 32
    /// The OAuth scope used when an authorization request does not provide one.
    public var DEFAULT_SCOPE = "openid ip:phone_verify"
    
    /// The coverage response timeout, in milliseconds.
    public var CoverageReadTimeout: TimeInterval = 10000
    /// The coverage connection timeout, in milliseconds.
    public var CoverageConnectTimeout: TimeInterval = 10000
    /// The authorization response timeout, in milliseconds.
    public var AuthReadTimeout: TimeInterval = 10000
    /// The authorization connection timeout, in milliseconds.
    public var AuthConnectTimeout: TimeInterval = 10000
    /// The time allowed for the first local-network permission prompt, in milliseconds.
    public var LocalNetworkPermissionFirstPromptTimeout: TimeInterval = 7000
    /// The local-network permission probe timeout, in milliseconds.
    public var LocalNetworkPermissionTimeout: TimeInterval = 1000
    /// Additional time allowed after the local-network permission prompt, in milliseconds.
    public var LocalNetworkPermissionGraceTimeout: TimeInterval = 3000
    
    /// The timeout for SDK error-report requests, in milliseconds.
    public var ErrorReportTimeout: TimeInterval = 10000
    
    /// An optional base URL used to construct service endpoints.
    public var BASE_URL : String? = nil
    /// The Keycloak realm name used to construct default service paths.
    public var REALM_NAME = "ipification" {
        didSet {
            updateRealmPaths()
        }
    }
    /// The relative path of the coverage endpoint.
    public var COVERAGE_PATH = "/auth/realms/ipification/coverage"
    /// The relative path of the OpenID Connect authorization endpoint.
    public var AUTH_PATH = "/auth/realms/ipification/protocol/openid-connect/auth"
    /// The relative path of the SDK log endpoint.
    public var SDK_LOG_PATH = "/auth/realms/ipification/sdk"
    /// A test-only suffix that forces a positive coverage result.
    public var COVERAGE_PATH_FORCED_TRUE = "/1.2.3.4"
    /// The complete coverage endpoint URL used by coverage requests.
    public var COVERAGE_URL: String = ""
    /// The complete authorization endpoint URL used by authorization requests.
    public var AUTHORIZATION_URL: String = ""
    /// The application redirect URI registered with IPification.
    public var REDIRECT_URI: String = ""
    /// The client identifier assigned to the integrating application.
    public var CLIENT_ID: String = ""

    /// The sandbox base URL for SMS authentication.
    public var SMS_BACKEND_URL_SANDBOX: String = ""
    /// The production base URL for SMS authentication.
    public var SMS_BACKEND_URL_PRODUCTION: String = ""
    /// The relative endpoint used to initiate SMS authentication.
    public var SMS_AUTH_PATH: String = "/sms/auth"
    /// The relative endpoint used to exchange an OTP for identity claims.
    public var SMS_TOKEN_PATH: String = "/sms/token"
    /// The default scope requested by SMS phone verification.
    public var SMS_SCOPE_VERIFY_PHONE: String = "openid ip:phone_verify"
    /// The preferred SMS authentication server identifier.
    public var SMS_SERVER_ID: String = "stage"
    /// The ordered authentication channels available to multi-channel authentication.
    public var AUTH_CHANNELS: [AuthChannel] = [.IP]
    
    @available(*, deprecated, message: "Use CONSENT_ID_VALUE instead")
    /// The legacy consent identifier. Use `CONSENT_ID_VALUE` instead.
    public var CONSENT_ID: String = "ipconsent001eng"

    
    /// The consent identifier included in authorization requests.
    public var CONSENT_ID_VALUE: String = "ipconsent001eng"
    
    /// The OAuth response type requested from the authorization server.
    public var RESPONSE_TYPE_VALUE : String = "code"
    
    /// The backend environment used when explicit URLs are not configured.
    public var ENV : IPEnvironment = IPEnvironment.PRODUCTION
    
    @available(*, deprecated, message: "Use IPLogs.sharedInstance.log instead")
    /// The legacy log buffer. Use `IPLogs.sharedInstance.log` instead.
    public var log = ""
    
    /// Forces coverage checks to use the positive-result test endpoint.
    public var coverageAlwaysTrue = false
    /// Controls whether the SDK verifies that configured messaging apps are installed.
    public var validateIMApps = true
    /// Controls whether instant-messaging authentication starts in automatic mode.
    public var IM_AUTO_MODE = false
    /// Messaging app identifiers ordered from highest to lowest priority.
    public var IM_PRIORITY_APP_LIST = [String]()
    /// Controls whether the SDK automatically opens the selected messaging app.
    public var ENABLE_AUTO_OPEN_IM_APP = false
    /// Enables verbose SDK diagnostics.
    public var debug = false
    
    /// Controls whether the SDK generates the OAuth state value automatically.
    public var automaticStateGenerationEnabled = true
    
    /// Indicates that `COVERAGE_URL` and `AUTHORIZATION_URL` were supplied directly.
    public var customUrls = false
    /// Stores the state value associated with the current authorization request.
    public var currentState = ""
    
    /// Controls client-side validation of required authorization parameters.
    public var enableParamsValidation = true
    /// Controls whether SDK-managed cookies are retained between requests.
    public var enableCookieHandling = false
    
    /// The process-wide SDK configuration instance.
    public static let sharedInstance = IPConfiguration()
    /// The user-defaults key used to track the local-network permission prompt.
    private let localNetworkPermissionPromptShownKey = "IPificationSDK.LocalNetworkPermissionPromptShown"
    /// The signature of the most recently generated header log.
    private var lastHeaderLogSignature: String?

    /// Indicates whether the SDK has previously displayed the local-network permission prompt.
    public var hasSeenLocalNetworkPermissionPrompt: Bool {
        return UserDefaults.standard.bool(forKey: localNetworkPermissionPromptShownKey)
    }

    /// Clears the stored local-network permission prompt state.
    public func resetLocalNetworkPermissionPromptTracking() {
        UserDefaults.standard.removeObject(forKey: localNetworkPermissionPromptShownKey)
    }

    internal func markLocalNetworkPermissionPromptSeen() {
        UserDefaults.standard.set(true, forKey: localNetworkPermissionPromptShownKey)
    }
    
    /// Controls whether the SDK sends diagnostic error reports to IPification.
    public var sendErrorReportsEnabled = true
    
    /// The sandbox endpoint used for SDK diagnostic reports.
    public var SDK_LOG_URL_STAGE = "https://api.stage.ipification.com/auth/realms/ipification/sdk"
    /// The production endpoint used for SDK diagnostic reports.
    public var SDK_LOG_URL_LIVE = "https://api.ipification.com/auth/realms/ipification/sdk"
    
    /// The maximum number of characters included in a diagnostic log payload.
    public var MAX_LOG_LENGTH = 300

    /// The diagnostic identifier for coverage API requests.
    let COVERAGE_API_STR = "COVERAGE"
    /// The diagnostic identifier for authorization API requests.
    let AUTH_API_STR = "AUTH"
    
    private override init() {
        super.init()
    }

    internal func defaultBaseUrl() -> String {
        return ENV == IPEnvironment.SANDBOX ? "https://api.stage.ipification.com" : "https://api.ipification.com"
    }

    private func updateRealmPaths() {
        let realmPath = "/auth/realms/\(REALM_NAME)"
        COVERAGE_PATH = realmPath + "/coverage"
        AUTH_PATH = realmPath + "/protocol/openid-connect/auth"
        SDK_LOG_PATH = realmPath + "/sdk"
        SDK_LOG_URL_STAGE = "https://api.stage.ipification.com" + SDK_LOG_PATH
        SDK_LOG_URL_LIVE = "https://api.ipification.com" + SDK_LOG_PATH
    }

    func initData(){
        
        // fix internal issue - START
        if customUrls == false {
            if(self.BASE_URL == nil){
                self.COVERAGE_URL = defaultBaseUrl() + self.COVERAGE_PATH
                if(coverageAlwaysTrue){
                    self.COVERAGE_URL = self.COVERAGE_URL + self.COVERAGE_PATH_FORCED_TRUE
                }
            } else {
                if(coverageAlwaysTrue){
                    self.COVERAGE_URL = (self.BASE_URL ?? "") + self.COVERAGE_PATH + self.COVERAGE_PATH_FORCED_TRUE
                } else {
                    self.COVERAGE_URL = (self.BASE_URL ?? "") + self.COVERAGE_PATH
                }
            }
        }
        
        if customUrls == false{
            if(self.BASE_URL == nil){
                self.AUTHORIZATION_URL = defaultBaseUrl() + self.AUTH_PATH
            } else {
                self.AUTHORIZATION_URL = (self.BASE_URL ?? "") + self.AUTH_PATH
            }
            
        }
        // fix internal issue - END
        
//        if(self.infoForKey("CLIENT_ID") != ""){
//            self.CLIENT_ID = self.infoForKey("CLIENT_ID")
//        }
        
//        if(self.infoForKey("REDIRECT_URI") != ""){
//            self.REDIRECT_URI = self.infoForKey("REDIRECT_URI")
//        }
//        
//        if(infoForKey("SEND_DEVICE_INFO") != ""){
//            self.enableCarrierHeaders = infoForKey("SEND_DEVICE_INFO") == "true"
//        }
    }
    
//    func infoForKey(_ key: String) -> String {
//        return (Bundle.main.infoDictionary?[key] as? String)?
//            .replacingOccurrences(of: "\\", with: "") ?? ""
//    }
    
//    public func generateState() -> String {
//        let letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
//        return String((0..<STATE_LENGTH).map{ _ in letters.randomElement()! })
//    }
    
    /// Generates a cryptographically random state value for an authorization request.
    public func generateState() -> String {
        var randomBytes = [UInt8](repeating: 0, count: STATE_LENGTH)
        let result = SecRandomCopyBytes(kSecRandomDefault, randomBytes.count, &randomBytes)
        
        func sanitize(_ string: String) -> String {
            return string
                .replacingOccurrences(of: "+", with: "A")
                .replacingOccurrences(of: "/", with: "B")
                .replacingOccurrences(of: "=", with: "C")
        }
        
        if result == errSecSuccess {
            var base64String = Data(randomBytes).base64EncodedString()
            
            if base64String.count > STATE_LENGTH {
                base64String = String(base64String.prefix(STATE_LENGTH))
            }
            
            return "ip-sdk-ios-a\(sanitize(base64String))"
        } else {
            // Fallback logic using letters and digits
            let letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
            let fallbackString = String((0..<STATE_LENGTH).map { _ in letters.randomElement()! })
            return "ip-sdk-ios-b\(fallbackString)"
        }
    }
    
    /// Appends a diagnostic summary of request and device headers to `IPLogs`.
    /// - Parameters:
    ///   - inputPhone: The phone number supplied to the authentication request.
    ///   - CLIENT_IP: The client IP address reported by the backend, when available.
    public func generateHeaderLogs(inputPhone: String, CLIENT_IP: String?) {
        let deviceInfo = IPHeaders.generate(headers: nil, true)
        let headerLogSignature = "\(IPConfiguration.sharedInstance.CLIENT_ID)|\(inputPhone)|\(CLIENT_IP ?? "")|\(deviceInfo[IPHeaders.WIFI_IP] ?? "")"
        if lastHeaderLogSignature == headerLogSignature && IPLogs.sharedInstance.log.isEmpty == false {
            return
        }
        lastHeaderLogSignature = headerLogSignature

        var log = ""
        
        log = "#####################################\n"
        log += "#####################################\n"
        
//        if (deviceInfo[IPHeaders.DUAL_SIM_PHONE] == "yes") {
//            log += "DUAL SIM: yes\n"
//            log += "ACTIVE MCC: \(deviceInfo[IPHeaders.ACTIVE_MCC] ?? "N/A")\n"
//            log += "ACTIVE MNC: \(deviceInfo[IPHeaders.ACTIVE_MNC] ?? "N/A")\n"
//            log += "ACTIVE COUNTRY NAME: \(deviceInfo[IPHeaders.ACTIVE_COUNTRY_NAME] ?? "N/A")\n"
//            log += "ACTIVE OPERATOR NAME: \(deviceInfo[IPHeaders.ACTIVE_OPERATOR_NAME] ?? "N/A")\n\n"
//            
//            log += "MCC SIM 1: \(deviceInfo[IPHeaders.MCC1] ?? "N/A")\n"
//            log += "MNC SIM 1: \(deviceInfo[IPHeaders.MNC1] ?? "N/A")\n"
//            log += "COUNTRY CODE SIM 1: \(deviceInfo[IPHeaders.SIM1_COUNTRY_NAME] ?? "N/A")\n"
//            log += "OPERATOR NAME SIM 1: \(deviceInfo[IPHeaders.SIM1_OPERATOR_NAME] ?? "N/A")\n\n"
//            
//            log += "MCC SIM 2: \(deviceInfo[IPHeaders.MCC2] ?? "N/A")\n"
//            log += "MNC SIM 2: \(deviceInfo[IPHeaders.MNC2] ?? "N/A")\n"
//            log += "COUNTRY CODE SIM 2: \(deviceInfo[IPHeaders.SIM2_COUNTRY_NAME] ?? "N/A")\n"
//            log += "OPERATOR NAME SIM 2: \(deviceInfo[IPHeaders.SIM2_OPERATOR_NAME] ?? "N/A")\n\n"
//            
//        } else {
//            log += "DUAL SIM: no\n"
//            log += "MCC: \(deviceInfo[IPHeaders.MCC1] ?? "N/A")\n"
//            log += "MNC: \(deviceInfo[IPHeaders.MNC1] ?? "N/A")\n"
//            log += "ACTIVE COUNTRY NAME: \(deviceInfo[IPHeaders.ACTIVE_COUNTRY_NAME] ?? "N/A")\n"
//            log += "ACTIVE OPERATOR NAME: \(deviceInfo[IPHeaders.ACTIVE_OPERATOR_NAME] ?? "N/A")\n"
//            
//            
//        }
        log += "-------------------------------------\n"
        log += "DEVICE NAME: \(deviceInfo[IPHeaders.DEVICE_NAME] ?? "N/A")\n"
        log += "OS VERSION: \(deviceInfo[IPHeaders.OS_VERSION] ?? "N/A")\n"
        
        log += "SDK VERSION: \(deviceInfo[IPHeaders.IP_SDK_VERSION] ?? "N/A")\n"
        log += "-------------------------------------\n"
        log += "CLIENT_ID: \(IPConfiguration.sharedInstance.CLIENT_ID)\n"
        log += "INPUT PHONE NUMBER: " + "\(inputPhone)\n"
        log += "CLIENT_IP: \(CLIENT_IP ?? "N/A")\n"
        log += "wifi-ip: \(deviceInfo[IPHeaders.WIFI_IP] ?? "N/A")\n"
        log += "#####################################\n"
        log += "#####################################\n\n"
        IPLogs.sharedInstance.append(log)
    }
}
