//
//  IPLogs.swift
//  IPificationSDK
//
//  Created by IPification on 5/7/24.
//  Copyright © 2024 IPification. All rights reserved.
//

import Foundation
/// Stores diagnostic output generated by the SDK.
public class IPLogs : NSObject {
    /// The serial queue that protects access to the log buffer.
    private let queue = DispatchQueue(label: "com.ipification.sdk.logs")
    /// The backing storage for accumulated log text.
    private var storage = ""

    /// The accumulated diagnostic log text.
    public var log: String {
        get {
            return queue.sync { storage }
        }
        set {
            queue.sync { storage = newValue }
        }
    }
    
    /// The process-wide diagnostic log store.
    public static let sharedInstance = IPLogs()

    /// The formatter used to timestamp diagnostic log entries.
    private static let timestampFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "dd/MM/yyyy HH:mm:ss.SSS"
        formatter.locale = Locale(identifier: "en_US_POSIX")
        return formatter
    }()

    /// Appends a message to the diagnostic log.
    public func append(_ message: String) {
        queue.sync {
            let line = "\(IPLogs.timestampFormatter.string(from: Date())) \(message)\n"
            storage += line
        }
    }

    /// Removes all accumulated diagnostic log text.
    public func clear() {
        queue.sync {
            storage = ""
        }
    }
}
